#!/usr/bin/env bash
#
# create-jambonz-secrets.sh
#
# One-time setup for deploying jambonz with secrets held in AWS SSM Parameter
# Store instead of generated by the CloudFormation stack. Run this BEFORE
# creating the stack, then supply the same path as the SecretsParameterPath
# stack parameter.
#
# You only need this if you want secrets managed outside the deployment - the
# usual reason is a compliance regime such as SOC 2, which wants secrets
# encrypted at rest under a key you control, every read recorded in CloudTrail,
# and credentials that can be rotated. If none of that applies, skip this
# script entirely and leave SecretsParameterPath blank; the stack will generate
# and manage a secret for you.
#
# Written for bash 3.2 so it runs on stock macOS as well as Linux.

set -euo pipefail

PATH_PREFIX=""
REGION=""
PROFILE=""
KMS_KEY_ID=""
FORCE="no"
DRY_RUN="no"

# BASIC_AUTH_PASSWORD and JAMBONZ_RECORD_WS_PASSWORD are a client/server pair -
# the feature server presents one to the recording service, which checks it
# against the other - so they MUST hold the same value.
REQUIRED_NAMES="ENCRYPTION_SECRET JWT_SECRET AUTHENTICATION_KEY JAMBONZ_RECORD_WS_PASSWORD BASIC_AUTH_PASSWORD"

usage() {
  cat <<'USAGE'
Usage: create-jambonz-secrets.sh --path <ssm-path> --region <aws-region> [options]

Required:
  --path <ssm-path>       Where to store the secrets, e.g. /jambonz/prod
                          Must start with / and must not end with /. Use a
                          distinct path per environment (/jambonz/prod,
                          /jambonz/staging) and per region.
  --region <aws-region>   Region the jambonz stack will be deployed in.
                          Parameter Store is regional: secrets must exist in
                          the same region as the stack.

Options:
  --profile <name>        AWS CLI profile to use.
  --kms-key-id <arn>      Full ARN of a customer managed KMS key to encrypt the
                          parameters with. Omit to use the AWS-managed key
                          (alias/aws/ssm), which is fine for most deployments.
                          If you supply one here, supply the same ARN as the
                          stack's KmsKeyId parameter.
  --force                 Overwrite parameters that already exist. See the
                          warning about ENCRYPTION_SECRET below.
  --dry-run               Show what would be created, change nothing.
  -h, --help              Show this help.

Example:
  ./create-jambonz-secrets.sh --path /jambonz/prod --region us-east-1

WARNING - ENCRYPTION_SECRET can never be changed once you have data.
  It encrypts stored credentials (speech and LLM API keys, and more) in the
  jambonz database. Changing it makes every one of those unreadable, and there
  is no recovery short of re-entering them all. --force is refused for this
  parameter unless you also pass --i-understand-encryption-secret-is-permanent.
USAGE
}

fail() { echo "ERROR: $*" >&2; exit 1; }

ACK_ENCRYPTION="no"
while [ $# -gt 0 ]; do
  case "$1" in
    --path)       PATH_PREFIX="${2:-}"; shift 2 ;;
    --region)     REGION="${2:-}"; shift 2 ;;
    --profile)    PROFILE="${2:-}"; shift 2 ;;
    --kms-key-id) KMS_KEY_ID="${2:-}"; shift 2 ;;
    --force)      FORCE="yes"; shift ;;
    --dry-run)    DRY_RUN="yes"; shift ;;
    --i-understand-encryption-secret-is-permanent) ACK_ENCRYPTION="yes"; shift ;;
    -h|--help)    usage; exit 0 ;;
    *)            echo "Unknown option: $1" >&2; echo; usage; exit 2 ;;
  esac
done

[ -n "$PATH_PREFIX" ] || { usage; exit 2; }
[ -n "$REGION" ]      || { usage; exit 2; }

case "$PATH_PREFIX" in
  /*) ;;
  *)  fail "--path must start with / (got '$PATH_PREFIX')" ;;
esac
case "$PATH_PREFIX" in
  */) fail "--path must not end with / (got '$PATH_PREFIX')" ;;
esac

command -v aws     >/dev/null 2>&1 || fail "the AWS CLI is required but was not found on PATH"
command -v openssl >/dev/null 2>&1 || fail "openssl is required but was not found on PATH"

AWS="aws --region $REGION"
[ -n "$PROFILE" ] && AWS="$AWS --profile $PROFILE"

CALLER=$($AWS sts get-caller-identity --query 'Arn' --output text 2>/dev/null) \
  || fail "could not authenticate to AWS. Check your credentials$([ -n "$PROFILE" ] && echo " for profile '$PROFILE'")."
ACCOUNT=$($AWS sts get-caller-identity --query 'Account' --output text)

echo "account : $ACCOUNT"
echo "identity: $CALLER"
echo "region  : $REGION"
echo "path    : $PATH_PREFIX"
if [ -n "$KMS_KEY_ID" ]; then echo "kms key : $KMS_KEY_ID"; else echo "kms key : (AWS-managed alias/aws/ssm)"; fi
echo

# ---- what already exists there? -------------------------------------------
EXISTING=$($AWS ssm get-parameters-by-path --path "$PATH_PREFIX" \
             --query 'Parameters[].Name' --output text 2>/dev/null || true)

encryption_exists="no"
for full in $EXISTING; do
  short=${full##*/}
  echo "already present: $short"
  [ "$short" = "ENCRYPTION_SECRET" ] && encryption_exists="yes"
done
[ -n "$EXISTING" ] && echo

if [ "$encryption_exists" = "yes" ] && [ "$FORCE" = "yes" ] && [ "$ACK_ENCRYPTION" != "yes" ]; then
  fail "ENCRYPTION_SECRET already exists at $PATH_PREFIX.
  Overwriting it will make every stored credential in an existing jambonz
  database permanently unreadable. If this path has never been used by a
  deployment, re-run with --i-understand-encryption-secret-is-permanent.
  If you are adding a second environment, use a different --path instead."
fi

if [ -n "$EXISTING" ] && [ "$FORCE" != "yes" ]; then
  fail "parameters already exist at $PATH_PREFIX. Re-run with --force to
  overwrite them, or choose a different --path for a new environment."
fi

# ---- generate --------------------------------------------------------------
# hex only: no newlines or tabs (the deploy-time helpers read these as
# KEY=value lines) and nothing that needs shell or sed quoting.
gen() { openssl rand -hex 32; }

V_ENCRYPTION_SECRET=$(gen)
V_JWT_SECRET=$(gen)
V_AUTHENTICATION_KEY=$(gen)
V_RECORD_PAIR=$(gen)     # shared by the two recording credentials, deliberately

value_for() {
  case "$1" in
    ENCRYPTION_SECRET)           echo "$V_ENCRYPTION_SECRET" ;;
    JWT_SECRET)                  echo "$V_JWT_SECRET" ;;
    AUTHENTICATION_KEY)          echo "$V_AUTHENTICATION_KEY" ;;
    JAMBONZ_RECORD_WS_PASSWORD)  echo "$V_RECORD_PAIR" ;;
    BASIC_AUTH_PASSWORD)         echo "$V_RECORD_PAIR" ;;
  esac
}

if [ "$DRY_RUN" = "yes" ]; then
  echo "dry run - would create these SecureString parameters:"
  for n in $REQUIRED_NAMES; do echo "  $PATH_PREFIX/$n"; done
  echo
  echo "(JAMBONZ_RECORD_WS_PASSWORD and BASIC_AUTH_PASSWORD would share one value)"
  exit 0
fi

# ---- write -----------------------------------------------------------------
for n in $REQUIRED_NAMES; do
  set -- --name "$PATH_PREFIX/$n" --value "$(value_for "$n")" --type SecureString --overwrite
  [ -n "$KMS_KEY_ID" ] && set -- "$@" --key-id "$KMS_KEY_ID"
  $AWS ssm put-parameter "$@" --query 'Version' --output text >/dev/null \
    || fail "failed writing $PATH_PREFIX/$n"
  echo "created $PATH_PREFIX/$n"
done
echo

# ---- verify ----------------------------------------------------------------
echo "verifying..."
PROBLEMS=0
for n in $REQUIRED_NAMES; do
  t=$($AWS ssm get-parameter --name "$PATH_PREFIX/$n" --query 'Parameter.Type' --output text 2>/dev/null || echo MISSING)
  if [ "$t" != "SecureString" ]; then
    echo "  FAIL $n is '$t', expected SecureString"
    PROBLEMS=$((PROBLEMS + 1))
  fi
done

a=$($AWS ssm get-parameter --name "$PATH_PREFIX/BASIC_AUTH_PASSWORD"        --with-decryption --query 'Parameter.Value' --output text)
b=$($AWS ssm get-parameter --name "$PATH_PREFIX/JAMBONZ_RECORD_WS_PASSWORD" --with-decryption --query 'Parameter.Value' --output text)
if [ "$a" != "$b" ]; then
  echo "  FAIL BASIC_AUTH_PASSWORD and JAMBONZ_RECORD_WS_PASSWORD differ - call recording will not work"
  PROBLEMS=$((PROBLEMS + 1))
fi

COUNT=$($AWS ssm get-parameters-by-path --path "$PATH_PREFIX" --query 'length(Parameters)' --output text)
if [ "$COUNT" -lt 5 ]; then
  echo "  FAIL expected at least 5 parameters under $PATH_PREFIX, found $COUNT"
  PROBLEMS=$((PROBLEMS + 1))
fi

if [ "$PROBLEMS" -ne 0 ]; then
  fail "$PROBLEMS verification problem(s) - do not deploy until these are resolved"
fi
echo "  all 5 parameters present, SecureString, recording pair matches"
echo

cat <<SUMMARY
Done. When you create the jambonz CloudFormation stack, set:

  SecretsParameterPath  =  $PATH_PREFIX
SUMMARY
[ -n "$KMS_KEY_ID" ] && echo "  KmsKeyId              =  $KMS_KEY_ID"
cat <<'NOTES'

Notes:
  - These parameters are regional. Deploying into another region, or building a
    standby site, means running this again there with the SAME values - jambonz
    cannot read a database encrypted under a different ENCRYPTION_SECRET.
  - JWT_SECRET, AUTHENTICATION_KEY, JAMBONZ_RECORD_WS_PASSWORD and
    BASIC_AUTH_PASSWORD can be rotated: update the parameter, then restart the
    jambonz apps to pick up the new value. Keep the last two identical.
  - ENCRYPTION_SECRET must never change once the deployment holds data.
  - The values are never printed by this script. To read one back deliberately:
      aws ssm get-parameter --name <path>/<NAME> --with-decryption \
        --query 'Parameter.Value' --output text
NOTES
