#!/bin/bash
# Enable SIP over TLS and WSS on this SBC.
# Generated by the jambonz CloudFormation launch template - do not edit
# here, edit the template and replace the instance.
set -o pipefail

DOMAIN="$1"
EMAIL="$2"
CONF_FILE=/etc/drachtio.conf.xml
SERVICE_FILE=/etc/systemd/system/drachtio.service
LIVE_DIR="/etc/letsencrypt/live/$DOMAIN"

if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
  echo "usage: $0 <sip-domain> <cert-email>" >&2
  exit 1
fi

# --- 1. certificate ------------------------------------------------
# Wildcard alongside the apex so each jambonz account can register
# under its own SIP realm. DNS-01 is the only challenge that issues a
# wildcard, and an SBC has no port 80 open, so it is also the only
# challenge available here.
if [ -d "$LIVE_DIR" ]; then
  echo "certificate for $DOMAIN already present, skipping certbot"
else
  if ! certbot certonly --non-interactive --agree-tos \
        --dns-route53 --dns-route53-propagation-seconds 60 \
        --email "$EMAIL" -d "$DOMAIN" -d "*.$DOMAIN"; then
    echo "ERROR: certbot failed, leaving drachtio without TLS" >&2
    exit 1
  fi
fi

# --- 2. <tls> block in drachtio.conf.xml ---------------------------
if grep -q "<tls>" "$CONF_FILE"; then
  echo "<tls> already present in $CONF_FILE"
else
  cp "$CONF_FILE" "$CONF_FILE.bak"
  TLS_BLOCK="    <tls>\n            <key-file>$LIVE_DIR/privkey.pem</key-file>\n            <cert-file>$LIVE_DIR/fullchain.pem</cert-file>\n            <chain-file>$LIVE_DIR/fullchain.pem</chain-file>\n        </tls>"
  sed -i "s|</sip>|$TLS_BLOCK\n    </sip>|" "$CONF_FILE"
  if grep -q "<tls>" "$CONF_FILE"; then
    echo "added <tls> to $CONF_FILE"
  else
    echo "ERROR: failed to add <tls> to $CONF_FILE, restoring backup" >&2
    mv "$CONF_FILE.bak" "$CONF_FILE"
    exit 1
  fi
fi

# --- 3. sips: contacts in drachtio.service -------------------------
if grep -q "transport=tls" "$SERVICE_FILE"; then
  echo "TLS contacts already present in $SERVICE_FILE"
else
  cp "$SERVICE_FILE" "$SERVICE_FILE.bak"
  sed -i '/--contact sip:${LOCAL_IP};transport=tcp/a --contact sips:${LOCAL_IP}:5061;transport=tls --external-ip ${PUBLIC_IP} \\\n--contact sips:${LOCAL_IP}:8443;transport=wss --external-ip ${PUBLIC_IP} \\' "$SERVICE_FILE"
  if grep -q "transport=tls" "$SERVICE_FILE"; then
    echo "added TLS/WSS contacts to $SERVICE_FILE"
  else
    echo "ERROR: could not find the tcp contact line to anchor on, restoring backup" >&2
    mv "$SERVICE_FILE.bak" "$SERVICE_FILE"
    exit 1
  fi
fi

# --- 4. restart drachtio after renewals ----------------------------
# certbot's own systemd timer renews the cert, but drachtio keeps
# serving the old one until it restarts. A deploy hook closes that gap.
mkdir -p /etc/letsencrypt/renewal-hooks/deploy
printf '%s\n' '#!/bin/bash' 'systemctl restart drachtio' \
  > /etc/letsencrypt/renewal-hooks/deploy/restart-drachtio.sh
chmod +x /etc/letsencrypt/renewal-hooks/deploy/restart-drachtio.sh
# Debian names the renewal unit certbot.timer, RHEL certbot-renew.timer.
# Without one of them nothing ever runs "certbot renew" and the hook above
# never fires, so say so loudly rather than failing silently.
systemctl enable --now certbot.timer 2>/dev/null \
  || systemctl enable --now certbot-renew.timer 2>/dev/null \
  || echo "WARNING: no certbot renewal timer found - the certificate will expire in 90 days"

systemctl daemon-reload
systemctl restart drachtio
echo "SIP TLS/WSS configured for $DOMAIN"
